export type QuizQuestion = {
  id: string;
  subject: string;
  prompt: string;
  options: string[];
  answer: number;
  explain: string;
};

export const SUBJECTS = ["current", "history", "geography", "polity", "economy", "science", "environment", "ethics"] as const;
export type QuizSubject = (typeof SUBJECTS)[number];

export function isQuizSubject(value: string): value is QuizSubject {
  return (SUBJECTS as readonly string[]).includes(value);
}

export const QUIZ_BANK: QuizQuestion[] = [
  {
    id: "cur-1",
    subject: "current",
    prompt: "While reading The Hindu / Indian Express for UPSC–BPSC, which mapping is most useful?",
    options: [
      "Copy the full report into notes",
      "Link the issue to a syllabus heading, constitutional/legal hook, and a way forward",
      "Memorise every statistic from the first paragraph",
      "Skip editorials and read only city briefs",
    ],
    answer: 1,
    explain: "Current affairs become GS marks when tied to syllabus, law/policy, and analysis—not transcription.",
  },
  {
    id: "cur-2",
    subject: "current",
    prompt: "PIB is most valuable in prelims–mains prep for:",
    options: ["Film reviews", "Official facts on schemes, indices and ministries", "Sports fixtures", "Stock tips"],
    answer: 1,
    explain: "Use PIB for authenticated scheme/data points; drop the publicity language.",
  },
  {
    id: "cur-3",
    subject: "current",
    prompt: "An editorial on federal friction between Centre and a state is primarily a question of:",
    options: ["GS-I culture", "GS-II polity and federalism", "GS-IV only", "Optional literature"],
    answer: 1,
    explain: "Centre–state issues sit in GS-II (federalism, Governor, finance, legislation).",
  },
  {
    id: "cur-4",
    subject: "current",
    prompt: "A report on Kosi floods should be filed under:",
    options: ["Only international relations", "Bihar geography + disaster management (GS-III)", "Medieval history", "Ethics thinkers"],
    answer: 1,
    explain: "BPSC/UPSC expect river, flood, and disaster-management linkages together.",
  },
  {
    id: "cur-5",
    subject: "current",
    prompt: "Weekly current-affairs revision is healthiest when you keep:",
    options: ["100 unedited clippings", "About 10 issues, 2 maps, 1 ethics case", "Only WhatsApp forwards", "No notes at all"],
    answer: 1,
    explain: "A thin, revised file beats an unread archive.",
  },
  {
    id: "cur-6",
    subject: "current",
    prompt: "Science news (ISRO launch, vaccine, AI regulation) is best noted as:",
    options: ["Application + regulation + equity", "Only the launch vehicle name", "Ignore unless it is a discovery in Europe", "A GS-I art question"],
    answer: 0,
    explain: "Mains GS-III wants use-case, governance, and inclusion—not trivia alone.",
  },
  {
    id: "his-1",
    subject: "history",
    prompt: "Magadha’s early rise is a BPSC favourite because it was centred around:",
    options: ["The Indus delta", "The mid-Ganga plains (Rajgir–Pataliputra)", "The Cauvery delta", "The Thar desert"],
    answer: 1,
    explain: "Iron, rivers, and political consolidation in the mid-Ganga basin explain Magadha.",
  },
  {
    id: "his-2",
    subject: "history",
    prompt: "Champaran Satyagraha (1917) is important because it:",
    options: ["Was Gandhi’s first mass satyagraha in India, on indigo", "Created the Indian National Army", "Ended the Delhi Sultanate", "Was a naval mutiny"],
    answer: 0,
    explain: "Champaran linked peasant distress in Bihar with Gandhi’s method.",
  },
  {
    id: "his-3",
    subject: "history",
    prompt: "Kunwar Singh is associated with 1857 operations around:",
    options: ["Peshawar", "Arrah–Jagdispur (Bihar)", "Mysore", "Guwahati"],
    answer: 1,
    explain: "BPSC often asks Bihar centres of 1857.",
  },
  {
    id: "his-4",
    subject: "history",
    prompt: "Ashoka’s dhamma is best described as:",
    options: ["A purely military doctrine", "Ethical-administrative policy after Kalinga", "A medieval Sufi order", "A British land revenue system"],
    answer: 1,
    explain: "Dhamma combined moral persuasion with imperial communication (edicts).",
  },
  {
    id: "his-5",
    subject: "history",
    prompt: "Nalanda and Vikramshila primarily illustrate:",
    options: ["Harappan dockyards", "Early medieval Buddhist learning in the Bihar–Bengal region", "Mughal painting ateliers", "Portuguese factories"],
    answer: 1,
    explain: "Both mahaviharas are core heritage–history overlap for BPSC.",
  },
  {
    id: "his-6",
    subject: "history",
    prompt: "Sher Shah’s administrative reputation rests partly on:",
    options: ["The Permanent Settlement of 1793", "Roads, currency and revenue experiments in the Bihar–Bengal tract", "The Ryotwari system of Munro", "Doctrine of Lapse"],
    answer: 1,
    explain: "Grand Trunk alignments, rupee, and sarkar–pargana ideas prefigure later Mughal practice.",
  },
  {
    id: "geo-1",
    subject: "geography",
    prompt: "The Kosi is called a ‘sorrow’ of Bihar mainly because of:",
    options: ["Tidal bores", "Avulsion, siltation and recurrent flooding", "Glacial outburst only in winter", "Salinity intrusion from the sea"],
    answer: 1,
    explain: "Himalayan load + shifting channels drive flood hazard in north Bihar.",
  },
  {
    id: "geo-2",
    subject: "geography",
    prompt: "Indian monsoon is fundamentally a:",
    options: ["Permanent high over the poles", "Seasonal reversal of winds tied to land–sea heating and ITCZ shift", "Daily land breeze only", "El Niño itself"],
    answer: 1,
    explain: "ENSO modulates the monsoon; it is not the monsoon mechanism.",
  },
  {
    id: "geo-3",
    subject: "geography",
    prompt: "North Bihar plains vs southern plateau fringe is a contrast of:",
    options: ["Coral vs atoll", "Alluvial floodplain vs Chhotanagpur-edge uplands", "Desert vs fjord", "Volcanic arc vs trench"],
    answer: 1,
    explain: "Know physiography for both maps and disaster questions.",
  },
  {
    id: "geo-4",
    subject: "geography",
    prompt: "Himalayan rivers differ from peninsular rivers mainly in:",
    options: ["Being rain-fed only and never snow-fed", "Antecedent/snow-fed regimes and larger sediment load", "Flowing west only", "Having no deltas"],
    answer: 1,
    explain: "Regime and geomorphology are standard prelims discriminators.",
  },
  {
    id: "geo-5",
    subject: "geography",
    prompt: "Bihar’s out-migration is best placed under:",
    options: ["Ocean currents", "Human geography: labour, remittances, urban pull", "Paleomagnetism", "Coral bleaching"],
    answer: 1,
    explain: "Link demography with economy papers.",
  },
  {
    id: "geo-6",
    subject: "geography",
    prompt: "Cyclones in the Bay of Bengal are a topic of:",
    options: ["Climatology and disaster management", "Harappan seals", "Directive Principles only", "WTO subsidies"],
    answer: 0,
    explain: "Physical process + IMD warnings + NDMA = GS-I/III combo.",
  },
  {
    id: "pol-1",
    subject: "polity",
    prompt: "The ‘basic structure’ doctrine is associated with:",
    options: ["Kesavananda Bharati (1973)", "Regulating Act 1773", "Lucknow Pact 1916", "Simon Commission 1927"],
    answer: 0,
    explain: "Parliament can amend, but not destroy, the Constitution’s basic structure.",
  },
  {
    id: "pol-2",
    subject: "polity",
    prompt: "73rd and 74th Amendments deal with:",
    options: ["GST Council", "Panchayats and municipalities", "Official language", "Emergency under Article 356 only"],
    answer: 1,
    explain: "Local government is a GS-II staple; Bihar PRIs appear in BPSC too.",
  },
  {
    id: "pol-3",
    subject: "polity",
    prompt: "Which pair is correctly matched?",
    options: [
      "CAG — audits government accounts",
      "EC — appoints Supreme Court judges",
      "UPSC — conducts state panchayat polls only",
      "NITI Aayog — is a constitutional body like Finance Commission",
    ],
    answer: 0,
    explain: "Know constitutional vs statutory vs extra-constitutional bodies.",
  },
  {
    id: "pol-4",
    subject: "polity",
    prompt: "Federal friction over Governors is primarily a question of:",
    options: ["Article on money bills in the UK", "Union–State executive and constitutional morality", "Harappan seals", "WTO SCM agreement"],
    answer: 1,
    explain: "Read with current affairs on state politics.",
  },
  {
    id: "pol-5",
    subject: "polity",
    prompt: "Fundamental Rights and DPSPs together illustrate:",
    options: ["That DPSPs always override rights", "A harmony-and-conflict theme (Minerva Mills etc.)", "That rights were added in 2017", "That DPSPs are justiciable like Article 32"],
    answer: 1,
    explain: "Prelims + Mains both test this balance.",
  },
  {
    id: "pol-6",
    subject: "polity",
    prompt: "RTI is a tool of:",
    options: ["Opacity in procurement", "Transparency and citizen-centric governance", "Martial law", "Optional literature"],
    answer: 1,
    explain: "Pair with CVC, CAG, Lokpal in governance notes.",
  },
  {
    id: "eco-1",
    subject: "economy",
    prompt: "Repo rate is primarily a:",
    options: ["Fiscal deficit target of the Budget", "Monetary policy rate at which RBI lends to banks against collateral", "GST slab", "Finance Commission grant"],
    answer: 1,
    explain: "Inflation–growth trade-off questions start here.",
  },
  {
    id: "eco-2",
    subject: "economy",
    prompt: "Fiscal deficit means:",
    options: ["Exports minus imports", "Government borrowing need: expenditure minus non-debt receipts", "Repo minus reverse repo", "CAD only"],
    answer: 1,
    explain: "Budget documents define this precisely.",
  },
  {
    id: "eco-3",
    subject: "economy",
    prompt: "Bihar’s economy notes should include:",
    options: ["Only Silicon Valley firms", "Agriculture specialities, migration remittances, and post-2005 governance/schemes", "North Sea oil", "Eurozone QE"],
    answer: 1,
    explain: "State-specific economy is a BPSC differentiator.",
  },
  {
    id: "eco-4",
    subject: "economy",
    prompt: "GST in India is best described as:",
    options: ["A destination-based indirect tax with dual Centre–State structure", "A direct tax on agricultural income of all farmers", "A local octroi revived in 2020", "A customs duty on coastal shipping only"],
    answer: 0,
    explain: "Federal design of GST is a GS-II/III overlap.",
  },
  {
    id: "eco-5",
    subject: "economy",
    prompt: "Inclusive growth questions often combine:",
    options: ["Poverty, jobs, inequality, and social sector outcomes", "Only Sensex closing", "Only gold imports", "Stamp collecting"],
    answer: 0,
    explain: "Use Survey and Budget for data; keep concepts clear.",
  },
  {
    id: "eco-6",
    subject: "economy",
    prompt: "MSP is closest to:",
    options: ["A floor support price announced for listed crops", "The reverse repo corridor", "SEBI’s listing fee", "A WTO ministerial declaration only"],
    answer: 0,
    explain: "Agriculture + food security is high-yield GS-III.",
  },
  {
    id: "sci-1",
    subject: "science",
    prompt: "PSLV is mainly used by ISRO as a:",
    options: ["Crewed deep-space habitat", "Workhorse launcher for many Earth-observation and nav sats", "Nuclear submarine", "Particle collider"],
    answer: 1,
    explain: "Map missions to applications (farming, disaster, navigation).",
  },
  {
    id: "sci-2",
    subject: "science",
    prompt: "Antimicrobial resistance (AMR) is a GS issue because it is:",
    options: ["A purely astronomical event", "A public-health + regulation + One-Health challenge", "A medieval tax", "An Article 370 matter"],
    answer: 1,
    explain: "Science current affairs → health policy.",
  },
  {
    id: "sci-3",
    subject: "science",
    prompt: "India Stack (Aadhaar, UPI etc.) is best revised under:",
    options: ["Digital public infrastructure, inclusion and data protection", "Paleolithic tools", "WTO textiles only", "Ocean trenches"],
    answer: 0,
    explain: "GS-II/III: governance + tech + privacy.",
  },
  {
    id: "sci-4",
    subject: "science",
    prompt: "Vaccines work primarily by:",
    options: ["Training adaptive immunity with antigen without causing full disease", "Replacing DNA in all cells overnight", "Blocking the monsoon", "Raising repo rate"],
    answer: 0,
    explain: "Class-X biology depth is enough for prelims if concepts are clean.",
  },
  {
    id: "sci-5",
    subject: "science",
    prompt: "Cyber security in GS-III is linked with:",
    options: ["Only cricket scores", "Critical infrastructure, data, and internal security", "Harappan weights", "Forest rights Act definitions only"],
    answer: 1,
    explain: "Pair with CERT-In, data protection, and critical sectors.",
  },
  {
    id: "sci-6",
    subject: "science",
    prompt: "GM crops debates in Mains need:",
    options: ["Yield/pest claims, biosafety regulation, and farmer equity", "Only brand names", "Ignoring ICAR/GEAC", "Treating it as GS-I art history"],
    answer: 0,
    explain: "Science + ethics + agriculture.",
  },
  {
    id: "env-1",
    subject: "environment",
    prompt: "Ramsar sites are related to:",
    options: ["Wetlands of international importance", "WTO agricultural boxes", "SEBI insider trading", "CAG audit paras"],
    answer: 0,
    explain: "Prelims loves conventions: Ramsar, CITES, CMS, UNFCCC.",
  },
  {
    id: "env-2",
    subject: "environment",
    prompt: "India’s climate pledge language (NDC) sits under:",
    options: ["UNFCCC Paris framework", "UNESCO heritage only", "ILO maritime convention", "Basel Committee on Banking"],
    answer: 0,
    explain: "Mitigation vs adaptation is the analytical split for Mains.",
  },
  {
    id: "env-3",
    subject: "environment",
    prompt: "EIA is:",
    options: ["A process to assess environmental impact before projects", "A monsoon index of IMD", "A type of cyclone", "A GST form"],
    answer: 0,
    explain: "Law + environment current affairs (notifications, exemptions).",
  },
  {
    id: "env-4",
    subject: "environment",
    prompt: "Bihar’s climate-risk notes should mention:",
    options: ["Only polar vortex", "Flood–heat–agriculture stress on the Ganga plains", "Permafrost in Patna", "Coral atolls of Gaya"],
    answer: 1,
    explain: "State geography + GS-III disaster management.",
  },
  {
    id: "env-5",
    subject: "environment",
    prompt: "Biodiversity hotspots require:",
    options: ["High endemic richness and habitat threat", "Zero species", "Only deserts", "Only urban CBDs"],
    answer: 0,
    explain: "Definition questions are common in prelims.",
  },
  {
    id: "env-6",
    subject: "environment",
    prompt: "NGT is a:",
    options: ["Specialised environmental tribunal", "New GST slab", "Naval task group of 1857", "Stock index"],
    answer: 0,
    explain: "Institutions + landmark orders appear in both papers.",
  },
  {
    id: "eth-1",
    subject: "ethics",
    prompt: "Conflict of interest in public office means:",
    options: ["Private interest may improperly influence official duty", "Working extra hours", "Reading newspapers", "Filing RTI as a citizen"],
    answer: 0,
    explain: "Define terms in your own words for GS-IV.",
  },
  {
    id: "eth-2",
    subject: "ethics",
    prompt: "A good ethics case-study method is:",
    options: ["Stakeholders → options → public interest → values", "Only quote slogans", "Ignore facts", "Always maximise personal career"],
    answer: 0,
    explain: "Structure scores more than moralising.",
  },
  {
    id: "eth-3",
    subject: "ethics",
    prompt: "Integrity is closest to:",
    options: ["Consistency of honest conduct even without supervision", "Winning an argument on TV", "Memorising more articles", "Avoiding all citizens"],
    answer: 0,
    explain: "Link to civil service values, not personality cults.",
  },
  {
    id: "eth-4",
    subject: "ethics",
    prompt: "Using a flood-relief or exam-conduct case from Bihar news is useful because:",
    options: ["It practises neutrality, compassion and rule of law together", "It replaces the entire GS-I syllabus", "It is prohibited", "It is only for optional anthropology"],
    answer: 0,
    explain: "Newspapers supply GS-IV case material if you strip partisanship.",
  },
  {
    id: "eth-5",
    subject: "ethics",
    prompt: "Emotional intelligence in administration helps mainly in:",
    options: ["Reading others’ affect and regulating one’s response under stress", "Calculating GDP deflator", "Drawing isobars", "Listing WTO rounds"],
    answer: 0,
    explain: "Keep the definition operational.",
  },
  {
    id: "eth-6",
    subject: "ethics",
    prompt: "Probity in governance emphasises:",
    options: ["Honesty, transparency and stewardship of public resources", "Maximum secrecy always", "Family first in contracts", "Ignoring CAG"],
    answer: 0,
    explain: "2nd ARC themes still pay in GS-IV.",
  },
  { id: "cur-7", subject: "current", prompt: "An Indian Express ‘Explained’ piece is most useful when you extract:", options: ["Only the headline", "The mechanism, stakeholders and policy hook", "Cricket scores in the sidebar", "The author’s Twitter handle"], answer: 1, explain: "Explained pages are built for GS: process + actors + law/policy." },
  { id: "cur-8", subject: "current", prompt: "A Supreme Court judgment in the newspaper should be filed first under:", options: ["Sports", "Polity / rights / federalism as per the issue", "Medieval architecture", "Optional mathematics"], answer: 1, explain: "Court news is GS-II unless it is purely trivia." },
  { id: "cur-9", subject: "current", prompt: "Budget-day reading should separate:", options: ["Memes from cricket", "Fiscal numbers, scheme redesigns, and federal transfers", "Only the finance minister’s clothing", "Only stock-market colour"], answer: 1, explain: "Budget is GS-III plus federalism (Finance Commission, GST)." },
  { id: "cur-10", subject: "current", prompt: "For BPSC, a Bihar-specific scheme in PIB should be noted with:", options: ["Only the logo", "Objective, ministry/department, and a development gap it targets", "English grammar errors", "Film celebrity ambassadors only"], answer: 1, explain: "State schemes need purpose + institutional home + outcome." },
  { id: "cur-11", subject: "current", prompt: "Climate COP coverage is best linked to:", options: ["UNFCCC/NDC and India’s energy mix", "Sangam poetry", "Article 370 only", "WTO textiles only"], answer: 0, explain: "Environment current affairs must sit on the convention + domestic policy." },
  { id: "his-7", subject: "history", prompt: "The Permanent Settlement (1793) primarily created:", options: ["Ryots as absolute owners everywhere", "Zamindars as revenue intermediaries in Bengal", "The ryotwari of Madras overnight", "Mughal jagirdari revival"], answer: 1, explain: "Cornwallis’ Bengal model is the classic colonial agrarian case." },
  { id: "his-8", subject: "history", prompt: "Bhakti and Sufi traditions matter for GS because they:", options: ["Are only temple architecture", "Show regional languages, social critique and overlapping sacred worlds", "Ended caste immediately", "Are unrelated to medieval polity"], answer: 1, explain: "Culture answers need social content, not only buildings." },
  { id: "his-9", subject: "history", prompt: "Harappan urbanism is identified archaeologically by:", options: ["Ashokan edicts", "Planned streets, drainage, weights and craft", "Iqta documents", "Permanent Settlement records"], answer: 1, explain: "No deciphered Harappan narrative texts; material culture leads." },
  { id: "his-10", subject: "history", prompt: "The Constituent Assembly is the hinge between:", options: ["Harappa and Magadha", "National movement and the Republic’s legal design", "Gupta art and Chola bronze", "WTO and RBI"], answer: 1, explain: "Class 12 ‘Framing the Constitution’ feeds Polity directly." },
  { id: "his-11", subject: "history", prompt: "Deindustrialisation under colonialism refers mainly to:", options: ["Growth of Indian mills only", "Decline of traditional crafts under unequal trade and tariffs", "Ashoka’s dhamma", "Green Revolution"], answer: 1, explain: "Modern economic history is half of GS-I/III overlap." },
  { id: "geo-7", subject: "geography", prompt: "Jet streams are important for the Indian monsoon because they:", options: ["Are ocean currents near Antarctica only", "Interact with the Tibetan heat low and monsoon onset/breaks", "Cause only desertification in Chile", "Are unrelated to rainfall"], answer: 1, explain: "Class 11 climatology is the physics behind newspaper monsoon stories." },
  { id: "geo-8", subject: "geography", prompt: "Alluvial soils of the Ganga plain are generally:", options: ["Laterite of the Western Ghats", "Fertile, renewed by floods, and the base of Bihar’s agriculture", "Pure desert sand", "Volcanic black soil only of Maharashtra"], answer: 1, explain: "Soils + floods + farming is one BPSC cluster." },
  { id: "geo-9", subject: "geography", prompt: "A rain-shadow region forms because of:", options: ["Orographic rainfall on the windward side and dry leeward air", "Tides", "Coral bleaching", "GST slabs"], answer: 0, explain: "Standard Class 7–11 rainfall type question." },
  { id: "geo-10", subject: "geography", prompt: "Demographic transition describes:", options: ["Plate tectonics", "Shift from high birth/death rates toward lower rates with development", "El Niño only", "Forest types"], answer: 1, explain: "Human geography Class 12." },
  { id: "geo-11", subject: "geography", prompt: "The Peninsular plateau is best described as:", options: ["A young fold mountain", "An old, relatively stable landmass with residual hills", "A coral atoll", "A rift exactly like East Africa in every detail"], answer: 1, explain: "Physiography contrast with Himalaya." },
  { id: "pol-7", subject: "polity", prompt: "A Money Bill under the Constitution can be introduced only in:", options: ["Rajya Sabha", "Lok Sabha", "A gram sabha", "NITI Aayog"], answer: 1, explain: "Article 110 procedure is a Prelims regular." },
  { id: "pol-8", subject: "polity", prompt: "Judicial review means courts can:", options: ["Collect GST", "Test laws and executive action against the Constitution", "Appoint District Collectors", "Print currency"], answer: 1, explain: "Basic feature linked to Kesavananda debates." },
  { id: "pol-9", subject: "polity", prompt: "The Finance Commission is:", options: ["A statutory company", "A constitutional body for Centre–State financial devolution", "An NGO", "A department of RBI"], answer: 1, explain: "Article 280; GS-II/III overlap." },
  { id: "pol-10", subject: "polity", prompt: "Anti-defection (Tenth Schedule) is aimed at:", options: ["River linking", "Curbing party-hopping in legislatures", "Forest rights", "WTO disputes"], answer: 1, explain: "Parliamentary functioning." },
  { id: "pol-11", subject: "polity", prompt: "Directive Principles are:", options: ["Fully justiciable like Article 32 always", "Non-justiciable goals that still guide the state", "Repealed in 1950", "Applicable only to Union Territories"], answer: 1, explain: "FR–DPSP harmony is a classic." },
  { id: "eco-7", subject: "economy", prompt: "CPI is used in India mainly to track:", options: ["Forest cover", "Retail inflation faced by consumers", "Fiscal deficit only", "Literacy"], answer: 1, explain: "Class 11 statistics + macro." },
  { id: "eco-8", subject: "economy", prompt: "The multiplier idea in Keynesian macro says:", options: ["Forests multiply rainfall instantly", "A rise in investment can raise income by more than itself via consumption", "Repo always equals CRR", "GDP ignores government"], answer: 1, explain: "Class 12 macro determination of income." },
  { id: "eco-9", subject: "economy", prompt: "Organised sector employment in India is:", options: ["Almost all workers", "A minority; most work remains informal", "Zero", "Only in agriculture"], answer: 1, explain: "Class 10/11 employment chapters." },
  { id: "eco-10", subject: "economy", prompt: "Current account in the BoP mainly records:", options: ["Only FDI", "Trade in goods/services and transfers, not the bulk of capital flows", "Only gold in Fort Knox", "State GST"], answer: 1, explain: "Open-economy macro." },
  { id: "eco-11", subject: "economy", prompt: "Human capital formation treats education and health as:", options: ["Pure consumption with no return", "Investment that raises productivity", "Only a cultural luxury", "Identical to mineral capital"], answer: 1, explain: "IED Class 11." },
  { id: "sci-7", subject: "science", prompt: "NavIC is best described as:", options: ["A river interlinking canal", "India’s regional navigation satellite system", "A GST form", "A cyclone name"], answer: 1, explain: "Space application, not trivia." },
  { id: "sci-8", subject: "science", prompt: "Photosynthesis in Class 10 science is the process by which:", options: ["Plants make food using light, CO₂ and water", "Earthquakes start", "Banks create credit", "Monsoons reverse"], answer: 0, explain: "Prelims still asks school science cleanly." },
  { id: "sci-9", subject: "science", prompt: "A semiconductor policy note for GS should mention:", options: ["Only cricket", "Fabs, supply chains, strategic dependence and incentives", "Megaliths", "Iqta"], answer: 1, explain: "S&T + industry + security." },
  { id: "sci-10", subject: "science", prompt: "mRNA vaccines differ from many traditional vaccines by:", options: ["Teaching cells to make an antigen briefly rather than injecting the whole pathogen always", "Being made of granite", "Replacing the Constitution", "Stopping the jet stream"], answer: 0, explain: "Mechanism + public health." },
  { id: "sci-11", subject: "science", prompt: "Earth observation satellites help Bihar mainly in:", options: ["Fashion weeks", "Flood mapping, crop and weather applications", "Minting coins", "Appointing Governors"], answer: 1, explain: "ISRO + disaster geography." },
  { id: "env-7", subject: "environment", prompt: "A biodiversity hotspot needs:", options: ["High endemism and serious habitat threat", "Zero species", "Only ice", "Only desert oil"], answer: 0, explain: "Definition from Class 11/12 environment chapters." },
  { id: "env-8", subject: "environment", prompt: "Mangroves matter because they:", options: ["Cause cyclones", "Buffer coasts, store carbon and host biodiversity", "Are identical to alpine forests", "Replace the monsoon"], answer: 1, explain: "Coasts + climate + disaster." },
  { id: "env-9", subject: "environment", prompt: "The polluter-pays idea is closest to:", options: ["Making those who pollute bear the cost of harm", "Free pollution for exporters", "Banning all industry always", "A Vedic tax"], answer: 0, explain: "Environment economics + law." },
  { id: "env-10", subject: "environment", prompt: "In-situ conservation means:", options: ["Zoos only", "Protecting species in their natural habitat (parks, reserves)", "Only DNA in a freezer abroad", "Crop insurance"], answer: 1, explain: "In-situ vs ex-situ." },
  { id: "env-11", subject: "environment", prompt: "PM2.5 refers to:", options: ["A finance commission grant", "Fine particulate matter that can enter lungs", "A river linking project", "A type of soil only"], answer: 1, explain: "Air pollution science for Prelims/Mains." },
  { id: "eth-7", subject: "ethics", prompt: "Objectivity in civil service means:", options: ["Ignoring the poor", "Deciding on evidence and rules, not personal liking", "Always following a party whip", "Never writing file notes"], answer: 1, explain: "Foundational value." },
  { "id": "eth-8", subject: "ethics", prompt: "A whistle-blower in administration is ethically linked to:", options: ["Gossip", "Exposing wrongdoing in public interest with due process", "Leaking for private revenge only", "Ignoring corruption"], answer: 1, explain: "Probity + protection debates." },
  { id: "eth-9", subject: "ethics", prompt: "Empathy differs from sympathy mainly because it:", options: ["Is identical to pity", "Tries to understand another’s situation from the inside, then act", "Is a fiscal deficit", "Is a monsoon type"], answer: 1, explain: "GS-IV vocabulary." },
  { id: "eth-10", subject: "ethics", prompt: "Work culture in a department improves most when:", options: ["Fear replaces rules", "Leadership models integrity, clarity and fair appraisal", "Files never move", "Everyone is related"], answer: 1, explain: "ARC and case studies." },
  { id: "eth-11", subject: "ethics", prompt: "Public service as trusteeship means officials:", options: ["Own the treasury privately", "Hold power and resources for citizens, not for self", "May auction posts", "Need not keep records"], answer: 1, explain: "Gandhian/constitutional ethic in GS-IV." },
];

export function publicQuestion(q: QuizQuestion) {
  return { id: q.id, subject: q.subject, prompt: q.prompt, options: q.options };
}

export function pickQuiz(subject: QuizSubject, count = 10) {
  const pool = QUIZ_BANK.filter((q) => q.subject === subject);
  const copy = [...pool];
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(count, copy.length));
}
