const officialUpsc = "https://www.upsc.gov.in/examinations/previous-question-papers";
const officialBpsc = "https://www.bpsc.bih.nic.in/";

function pre(exam, year, paper, questions, note) {
  return {
    exam,
    year,
    stage: "prelims",
    paper,
    official: exam === "upsc" ? officialUpsc : officialBpsc,
    note,
    questions: questions.map((q, i) => ({
      id: `${exam}-pre-${year}-${i + 1}`,
      n: i + 1,
      q: q.q,
      options: q.options,
      answer: q.answer,
      topic: q.topic || "GS",
      solution: q.solution,
    })),
  };
}

function mains(exam, year, paper, questions, note) {
  return {
    exam,
    year,
    stage: "mains",
    paper,
    official: exam === "upsc" ? officialUpsc : officialBpsc,
    note,
    questions: questions.map((q, i) => ({
      id: `${exam}-mains-${year}-${paper}-${i + 1}`,
      n: i + 1,
      q: q.q,
      marks: q.marks,
      topic: q.topic || paper,
      solution: q.solution,
    })),
  };
}

const upscPrelims = [
  pre("upsc", 2025, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "With reference to the Constitution of India, the Ninth Schedule was originally intended to protect which class of laws from judicial review?",
      options: ["Electoral laws only", "Land-reform and related laws placed in it", "All money bills", "Ordinance-making powers"],
      answer: 1,
      solution: "Correct option: B. The First Amendment (1951) added the Ninth Schedule mainly to shield agrarian reform laws. Later jurisprudence (I.R. Coelho) held that even these laws can be tested against basic structure.",
    },
    {
      topic: "Economy",
      q: "Which of the following best describes the role of the Monetary Policy Committee (MPC) in India?",
      options: ["It votes the Union Budget", "It sets the policy repo rate to meet the inflation target", "It fixes MSP for all crops", "It appoints the CAG"],
      answer: 1,
      solution: "Correct option: B. The MPC (RBI Act) decides the repo rate to keep CPI inflation around the 4% target with a ±2% band. Fiscal choices remain with the government.",
    },
    {
      topic: "Environment",
      q: "The Paris Agreement is legally anchored in which climate convention?",
      options: ["Montreal Protocol", "UNFCCC", "Kyoto Protocol only, with no UNFCCC link", "Basel Convention"],
      answer: 1,
      solution: "Correct option: B. Paris (2015) is an agreement under the UNFCCC. NDCs are nationally determined; Kyoto was the earlier protocol with annex-based targets.",
    },
    {
      topic: "History",
      q: "The Champaran Satyagraha (1917) was primarily concerned with:",
      options: ["Salt tax in Gujarat", "Indigo planters’ tinkathia system in Bihar", "Rowlatt Act all-India", "Simon Commission boycott"],
      answer: 1,
      solution: "Correct option: B. Gandhi’s first satyagraha in India targeted forced indigo cultivation. It is a BPSC/UPSC favourite bridge between modern India and Bihar.",
    },
    {
      topic: "Geography",
      q: "El Niño is best described as:",
      options: ["A permanent cold current off Peru", "A periodic warming of the central/eastern equatorial Pacific that can disturb Indian monsoon probabilities", "A Himalayan jet stream", "A type of cyclone in the Bay of Bengal only"],
      answer: 1,
      solution: "Correct option: B. ENSO is a coupled ocean–atmosphere oscillation. El Niño raises the chance of a weak monsoon; it is not a guarantee of drought everywhere.",
    },
    {
      topic: "S&T",
      q: "NavIC is:",
      options: ["A river-linking canal in north Bihar", "India’s regional satellite navigation system", "A GST form", "A cyclone name list"],
      answer: 1,
      solution: "Correct option: B. Navigation with Indian Constellation is ISRO’s regional GNSS. Map it to applications (timing, disaster, transport), not only satellite nicknames.",
    },
    {
      topic: "Polity",
      q: "A Money Bill under Article 110 can be introduced only in:",
      options: ["Rajya Sabha", "Lok Sabha", "A joint sitting first", "NITI Aayog"],
      answer: 1,
      solution: "Correct option: B. Money Bills originate in the Lok Sabha on the President’s recommendation. Rajya Sabha can only recommend; it cannot reject.",
    },
    {
      topic: "Environment",
      q: "Ramsar sites are wetlands of international importance under a convention signed at:",
      options: ["Kyoto", "Ramsar (Iran)", "Stockholm only", "Paris"],
      answer: 1,
      solution: "Correct option: B. The Ramsar Convention (1971) lists wetlands. India has many Ganga-basin sites relevant to Bihar/UP floodplain ecology.",
    },
  ], "High-yield 2025-cycle GS items with PrepHaat solutions. Full booklet: upsc.gov.in."),
  pre("upsc", 2023, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Consider the following statements about the Finance Commission: 1. It is a constitutional body. 2. It recommends distribution of tax proceeds between Union and States. Which is/are correct?",
      options: ["1 only", "2 only", "Both 1 and 2", "Neither"],
      answer: 2,
      solution: "Correct option: C. Article 280 creates the Finance Commission. Vertical and horizontal devolution, plus grants, are its core. GST Council is a different federal body.",
    },
    {
      topic: "Polity",
      q: "Which of the following is/are listed as Fundamental Duties in Article 51A?",
      options: ["To pay GST on time", "To safeguard public property and abjure violence", "To contest elections", "To hold a passport"],
      answer: 1,
      solution: "Correct option: B. 51A includes respect for the Constitution, composite culture, environment, scientific temper, public property, and education of children (86th Amendment), among others.",
    },
    {
      topic: "Geography",
      q: "The ‘ring of fire’ is associated with:",
      options: ["The Sahara", "Circum-Pacific plate boundaries with volcanoes and earthquakes", "Only the Alps", "The Ganga delta"],
      answer: 1,
      solution: "Correct option: B. Convergent Pacific margins explain most of the world’s stratovolcanoes and great earthquakes.",
    },
    {
      topic: "History",
      q: "The Cabinet Mission (1946) proposed:",
      options: ["Immediate Partition into two dominions only", "A three-tier federal structure and a Constituent Assembly", "Dyarchy in provinces", "Subsidiary Alliance"],
      answer: 1,
      solution: "Correct option: B. Cabinet Mission rejected Pakistan as then demanded, suggested groups of provinces, and a Constituent Assembly — the hinge into Constitution-making.",
    },
    {
      topic: "Economy",
      q: "Core inflation typically excludes:",
      options: ["Services", "Food and fuel prices that are very volatile", "Housing", "All manufactured goods"],
      answer: 1,
      solution: "Correct option: B. Core CPI is headline inflation minus food and energy so that MPC can see underlying demand pressure.",
    },
    {
      topic: "Environment",
      q: "In-situ conservation refers to:",
      options: ["Zoos and seed banks only", "Protecting species in their natural habitat (national parks, sanctuaries)", "Only DNA stored abroad", "Crop insurance"],
      answer: 1,
      solution: "Correct option: B. National parks, sanctuaries, biosphere reserves are in-situ. Ex-situ is zoos, gene banks, botanic gardens.",
    },
    {
      topic: "S&T",
      q: "mRNA vaccines work primarily by:",
      options: ["Inserting a live virus that always causes disease", "Instructing cells to make an antigen so adaptive immunity is trained", "Replacing the entire human genome", "Blocking the monsoon jet stream"],
      answer: 1,
      solution: "Correct option: B. A short-lived mRNA template produces spike (or other) protein; it does not alter DNA.",
    },
    {
      topic: "Polity",
      q: "The basic structure doctrine was laid down in:",
      options: ["A.K. Gopalan", "Kesavananda Bharati (1973)", "Shankari Prasad", "Golaknath only, with no later case"],
      answer: 1,
      solution: "Correct option: B. Parliament may amend under 368 but cannot destroy basic structure. Later cases applied it to Ninth Schedule, NJAC, etc.",
    },
  ], "Selected official-style 2023 GS items with solutions."),
  pre("upsc", 2022, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Attorney-General of India: which is correct?",
      options: ["He is a full-time minister", "He has the right to speak in Parliament but not to vote", "He is appointed by the CJI", "He heads the CBI"],
      answer: 1,
      solution: "Correct option: B. Article 76: the AG is the Union’s lawyer, enjoys audience in all courts, and may participate in Parliament without a vote.",
    },
    {
      topic: "Polity",
      q: "Which of the following is a Constitutional body?",
      options: ["NITI Aayog", "Election Commission of India", "NGT", "SEBI"],
      answer: 1,
      solution: "Correct option: B. ECI is in Part XV. NITI is executive; NGT and SEBI are statutory.",
    },
    {
      topic: "Geography",
      q: "La Niña is generally associated with:",
      options: ["Warm eastern Pacific", "Cooler than average eastern equatorial Pacific, often boosting Indian monsoon chances", "Only Himalayan glaciation", "A GST slab"],
      answer: 1,
      solution: "Correct option: B. La Niña is the cold phase of ENSO. Treat it as a probability shifter, not a rainfall guarantee.",
    },
    {
      topic: "History",
      q: "Who among the following organised the Home Rule Movement in India?",
      options: ["Only Subhas Bose in 1943", "Annie Besant and Bal Gangadhar Tilak (among others)", "Cornwallis", "Mountbatten"],
      answer: 1,
      solution: "Correct option: B. Home Rule Leagues (1916) demanded self-government within the Empire and revived Extremists after 1907.",
    },
    {
      topic: "Economy",
      q: "GST in India is best described as:",
      options: ["A central sales tax only", "A destination-based dual indirect tax levied by Union and States", "A tax on agricultural land", "A customs duty on services only"],
      answer: 1,
      solution: "Correct option: B. Dual GST (CGST+SGST) or IGST on inter-State supply; GST Council is the federal bargain.",
    },
    {
      topic: "Environment",
      q: "PM2.5 refers to:",
      options: ["A Finance Commission grant", "Fine particulate matter that can enter deep into the lungs", "A river-linking project", "A soil order"],
      answer: 1,
      solution: "Correct option: B. Particles ≤2.5 μm drive NCAP and AQI debates. Pair with sources: vehicles, biomass, industry, dust.",
    },
    {
      topic: "S&T",
      q: "Web 3.0 discussions in GS often involve:",
      options: ["Only steam engines", "Decentralised protocols, digital public infrastructure and data rights", "Iqta", "Megaliths"],
      answer: 1,
      solution: "Correct option: B. Write application + regulation (data protection, cyber) + inclusion, not jargon.",
    },
    {
      topic: "Polity",
      q: "Anti-defection law is in:",
      options: ["Eighth Schedule", "Tenth Schedule", "Twelfth Schedule", "Preamble only"],
      answer: 1,
      solution: "Correct option: B. 52nd Amendment; 91st tweaked. Speaker/Chair decides; courts have reviewed the process (Kihoto, later cases).",
    },
  ], "Selected 2022 GS items with solutions."),
  pre("upsc", 2021, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Right to Property in India today is:",
      options: ["A Fundamental Right in Part III", "A constitutional legal right under Article 300A", "Not recognised at all", "Only a DPSP"],
      answer: 1,
      solution: "Correct option: B. 44th Amendment removed 19(1)(f)/31 from FRs. 300A still requires authority of law to deprive a person of property.",
    },
    {
      topic: "History",
      q: "The Indus Waters Treaty (1960) allocated to India the use of:",
      options: ["All six rivers exclusively", "The eastern rivers (Ravi, Beas, Sutlej) with specified rights on the western rivers", "Only the Kabul river", "Only groundwater"],
      answer: 1,
      solution: "Correct option: B. World Bank-brokered treaty. Western rivers (Indus, Jhelum, Chenab) are largely for Pakistan with Indian limited uses.",
    },
    {
      topic: "Economy",
      q: "Fiscal deficit is:",
      options: ["Exports minus imports", "Government’s total expenditure minus total receipts except borrowings", "Repo minus reverse repo", "CAD"],
      answer: 1,
      solution: "Correct option: B. It is the borrowing requirement. Revenue deficit and primary deficit are related but not identical.",
    },
    {
      topic: "Geography",
      q: "Black cotton soils (regur) in India are mainly associated with:",
      options: ["Laterite of Meghalaya only", "Deccan trap / basalt regions, good for cotton", "Pure desert sand of Jaisalmer only", "Peat of Kerala backwaters only"],
      answer: 1,
      solution: "Correct option: B. Weathered basalt, moisture-retentive, cracks in summer. Contrast with alluvium of the Ganga plain.",
    },
    {
      topic: "Environment",
      q: "The Montreal Protocol is aimed at:",
      options: ["Climate finance only", "Phasing out ozone-depleting substances", "WTO agriculture", "Cyber crime"],
      answer: 1,
      solution: "Correct option: B. ODS (CFCs etc.). Kigali Amendment later added HFCs (climate, not ozone). Do not mix with UNFCCC.",
    },
    {
      topic: "S&T",
      q: "CRISPR is:",
      options: ["A medieval tax", "A genome-editing tool with agriculture/health uses and biosafety issues", "A cyclone category", "A type of monsoon"],
      answer: 1,
      solution: "Correct option: B. Write GEAC/ethics/IPR beside the mechanism.",
    },
    {
      topic: "Polity",
      q: "Which House is called a permanent House?",
      options: ["Lok Sabha", "Rajya Sabha", "Both dissolve together always", "Gram Sabha"],
      answer: 1,
      solution: "Correct option: B. One-third of Rajya Sabha retires every two years; it is not subject to dissolution like Lok Sabha.",
    },
    {
      topic: "History",
      q: "Mahatma Gandhi was first called ‘Father of the Nation’ in a public political context most famously associated with:",
      options: ["Only British Viceroys", "Netaji Subhas Chandra Bose’s radio address from abroad (among popular attributions)", "Ashoka’s edicts", "The Subsidiary Alliance"],
      answer: 1,
      solution: "Correct option: B. The popular attribution is Bose, 1944. UPSC may still prefer a careful ‘often attributed’ framing in Mains.",
    },
  ], "Selected 2021 GS items with solutions."),
  pre("upsc", 2020, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Rajya Sabha has exclusive power to:",
      options: ["Impeach the President alone without Lok Sabha", "Pass a resolution to create an All-India Service (Article 312)", "Pass a Money Bill", "Appoint the Prime Minister"],
      answer: 1,
      solution: "Correct option: B. Special powers: 249 (Rajya Sabha can authorise Parliament to legislate on a State List matter in national interest) and 312.",
    },
    {
      topic: "Geography",
      q: "The Atal Tunnel is associated with:",
      options: ["Connecting the mainland to Sri Lanka", "Rohtang / Manali–Lahaul access, all-weather road to the Himalayan interior", "Suez Canal", "Konkan railway"],
      answer: 1,
      solution: "Correct option: B. High-altitude highway tunnel; disaster and logistics geography for Himachal–Ladakh access.",
    },
    {
      topic: "History",
      q: "The Government of India Act, 1935 provided for:",
      options: ["Immediate complete independence", "Provincial autonomy and a proposed All-India Federation (which never fully came into being)", "Only Rule of the Company", "Abolition of princely states"],
      answer: 1,
      solution: "Correct option: B. Provincial autonomy from 1937; Centre remained constrained. It heavily influenced the 1950 Constitution’s federal lists.",
    },
    {
      topic: "Economy",
      q: "Which of the following is a function of SEBI?",
      options: ["Print currency", "Regulate the securities market and protect investors", "Set repo rate", "Collect income tax"],
      answer: 1,
      solution: "Correct option: B. Statutory regulator. RBI is monetary/banking; CBDT is direct tax.",
    },
    {
      topic: "Environment",
      q: "Nationally Determined Contributions (NDCs) belong to:",
      options: ["WTO", "Paris Agreement / UNFCCC process", "ILO only", "UNESCO heritage"],
      answer: 1,
      solution: "Correct option: B. Each party files NDCs; India has energy-intensity, non-fossil capacity and sink-related pledges that evolve over cycles.",
    },
    {
      topic: "S&T",
      q: "Fifth-generation fighter aircraft are generally characterised by:",
      options: ["Only propeller engines", "Stealth, sensor fusion and supermaneuverability (among other traits)", "Being identical to WWI biplanes", "Running on coal"],
      answer: 1,
      solution: "Correct option: B. Tejas Mk-1 is not fifth generation; do not confuse with Rafale/Su-30 class either.",
    },
    {
      topic: "Polity",
      q: "Preamble to the Indian Constitution declares India to be:",
      options: ["A monarchy", "Sovereign Socialist Secular Democratic Republic (after 42nd Amendment words)", "A theocracy", "A confederation of princely states"],
      answer: 1,
      solution: "Correct option: B. 42nd Amendment inserted Socialist and Secular. Kesavananda treated Preamble as a key to basic structure.",
    },
    {
      topic: "Geography",
      q: "Western Disturbances affecting north India in winter originate over:",
      options: ["The Bay of Bengal only", "The Mediterranean / West Asian region and travel east in the westerlies", "El Niño directly as a cyclone in Odisha", "The Equator as trade winds only"],
      answer: 1,
      solution: "Correct option: B. Extra-tropical systems that bring winter rain/snow to NW India and sometimes Bihar’s western fringe.",
    },
  ], "Selected 2020 GS items with solutions."),
  pre("upsc", 2019, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Which Article is the principal home of the right to marry a person of one’s choice, as read by the Supreme Court in the Hadiya matter?",
      options: ["Article 14 only, with no liberty clause", "Article 21", "Article 32 only", "Article 368"],
      answer: 1,
      solution: "Correct option: B. Liberty under 21 includes choice in marriage, subject to valid law. Pair with Puttaswamy (privacy).",
    },
    {
      topic: "History",
      q: "The term ‘Ahrar’ and ‘Rihai’ in the context of Indian national movement are associated with:",
      options: ["Indigo satyagraha only", "Khilafat / Muslim political currents of the early 20th century", "Gupta land grants", "Harappan seals"],
      answer: 1,
      solution: "Correct option: B. UPSC often pulls lesser-known organisational names from modern India — revise Spectrum’s organisations lists.",
    },
    {
      topic: "Economy",
      q: "Which of the following is issued by a commercial bank?",
      options: ["Treasury bills of the Government of India as owner", "Certificates of deposit (among bank instruments)", "Sovereign gold bonds as issuer of last resort", "Union Budget"],
      answer: 1,
      solution: "Correct option: B. CDs are negotiable money-market instruments issued by banks. T-bills are government paper.",
    },
    {
      topic: "Environment",
      q: "Which of the following are in the IUCN Red List categories?",
      options: ["Only ‘safe’", "Vulnerable, Endangered, Critically Endangered (among others)", "Only ‘domesticated’", "Only ‘invasive’"],
      answer: 1,
      solution: "Correct option: B. Prelims loves the ladder: LC, NT, VU, EN, CR, EW, EX.",
    },
    {
      topic: "Geography",
      q: "The Strait of Hormuz is strategically important because it:",
      options: ["Links the Mediterranean to the Black Sea", "Is a chokepoint for Persian Gulf oil to the open ocean", "Separates Sri Lanka from India", "Is an Indian inland canal"],
      answer: 1,
      solution: "Correct option: B. IR + geography: energy security and naval presence.",
    },
    {
      topic: "Polity",
      q: "Which of the following statements about the Comptroller and Auditor General is correct?",
      options: ["CAG is appointed by the Prime Minister alone without the President", "CAG audits government accounts and reports to the President who lays them in Parliament", "CAG collects GST", "CAG sits in the Union Cabinet"],
      answer: 1,
      solution: "Correct option: B. Articles 148–151. Independence is a basic-structure flavour issue in Mains.",
    },
    {
      topic: "S&T",
      q: "Digital Public Infrastructure in India is illustrated by:",
      options: ["Only Ashokan pillars", "Aadhaar, UPI and related India Stack building blocks", "Iqta", "Permanent Settlement"],
      answer: 1,
      solution: "Correct option: B. Inclusion plus exclusion errors, consent and cyber risk belong in the same note.",
    },
    {
      topic: "History",
      q: "The Battle of Plassey (1757) is important because it:",
      options: ["Ended the Mauryan empire", "Opened Bengal to Company political power after a palace conspiracy and military clash", "Created the UN", "Started the Gupta age"],
      answer: 1,
      solution: "Correct option: B. Follow with Buxar (1764) and Diwani (1765) for the Company-as-state story.",
    },
  ], "Selected 2019 GS items with solutions."),
  pre("upsc", 2018, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Which of the following are the core organs of the United Nations?",
      options: ["Only UNESCO", "General Assembly, Security Council, ECOSOC, Secretariat, ICJ (and Trusteeship Council still listed)", "Only NATO", "Only WTO"],
      answer: 1,
      solution: "Correct option: B. Six organs in the Charter; Trusteeship is inactive. Prelims still asks the list.",
    },
    {
      topic: "Polity",
      q: "The Supreme Court’s judgement in Justice K.S. Puttaswamy (Retd.) vs Union of India is related to:",
      options: ["Abolition of titles", "Right to privacy as a Fundamental Right", "GST rates", "River water disputes only"],
      answer: 1,
      solution: "Correct option: B. Nine-judge Bench, 2017: privacy in 14/19/21. Foundation for Aadhaar, data protection and later cases.",
    },
    {
      topic: "Economy",
      q: "Which one of the following best describes ‘inclusive growth’?",
      options: ["Growth of Sensex only", "Growth that expands income with equity in jobs, health and education", "Only gold imports", "Inflation targeting alone"],
      answer: 1,
      solution: "Correct option: B. Survey language: employment, social sector, regional balance — not GDP alone.",
    },
    {
      topic: "Environment",
      q: "The ‘Bio-diversity Act’ of India was enacted in:",
      options: ["1950", "2002", "2016 as the first environmental law", "1935"],
      answer: 1,
      solution: "Correct option: B. Biological Diversity Act, 2002 implements CBD: NBA, SBBs, BMCs, ABS.",
    },
    {
      topic: "Geography",
      q: "Which of the following is a west-flowing river of the Peninsula?",
      options: ["Godavari", "Narmada", "Mahanadi", "Kaveri"],
      answer: 1,
      solution: "Correct option: B. Narmada and Tapi flow west in rift valleys. Most large peninsular rivers drain east to the Bay.",
    },
    {
      topic: "History",
      q: "The well-known painting ‘Bani Thani’ belongs to the:",
      options: ["Kangra school only", "Kishangarh school of Rajasthan", "Bengal school of Abanindranath only", "Patna Kalam only"],
      answer: 1,
      solution: "Correct option: B. Culture Prelims: school + region + patron. Kishangarh’s elongated lyrical style.",
    },
    {
      topic: "S&T",
      q: "‘3D printing’ has applications in:",
      options: ["Only cooking oil", "Prototyping, medical implants and selected manufacturing, with IP and safety issues", "Only monsoon forecasting", "Minting coins by RBI mandatorily"],
      answer: 1,
      solution: "Correct option: B. Additive manufacturing: GS-III industry + S&T.",
    },
    {
      topic: "Polity",
      q: "Which of the following is not a Fundamental Right in India?",
      options: ["Right to equality", "Right to property (as FR)", "Right to freedom of religion", "Right against exploitation"],
      answer: 1,
      solution: "Correct option: B. Property is 300A, not Part III, after the 44th Amendment.",
    },
  ], "Selected 2018 GS items with solutions."),
  pre("upsc", 2017, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Which of the following statements about the Election Commission is correct?",
      options: ["It is a statutory company", "It is a constitutional body that superintends elections to Parliament, State legislatures and the offices of President and VP", "It conducts panchayat elections in every State by itself", "It is headed by the Law Minister"],
      answer: 1,
      solution: "Correct option: B. Article 324. Local body elections are with State Election Commissions (73rd/74th).",
    },
    {
      topic: "Geography",
      q: "Which of the following is/are tributaries of the Brahmaputra?",
      options: ["Only Yamuna", "Lohit, Dibang and Subansiri (among others)", "Only Narmada", "Only Cauvery"],
      answer: 1,
      solution: "Correct option: B. NE drainage is a Prelims map staple. In Bangladesh it becomes Jamuna.",
    },
    {
      topic: "History",
      q: "The ‘Swadeshi Movement’ is most closely associated with the partition of:",
      options: ["Punjab in 1947 only", "Bengal in 1905", "Bombay Presidency", "Madras in 1639"],
      answer: 1,
      solution: "Correct option: B. 1905 Partition → Swadeshi and boycott, Extremists vs Moderates, later 1911 reunification.",
    },
    {
      topic: "Economy",
      q: "Which of the following is the function of the RBI?",
      options: ["Pass the Union Budget", "Banker to the government and manager of foreign exchange (among other functions)", "Appoint Supreme Court judges", "Conduct Census"],
      answer: 1,
      solution: "Correct option: B. Monetary authority, issuer of currency, banker to banks, public debt manager, forex.",
    },
    {
      topic: "Environment",
      q: "The term ‘Domestic Content Requirement’ is sometimes seen in the news in the context of:",
      options: ["Inducing locally manufactured solar equipment / WTO disputes", "MSP of wheat only", "Article 370", "Forest Rights Act definitions only"],
      answer: 1,
      solution: "Correct option: A. India–US solar WTO dispute is the classic GS-III hook.",
    },
    {
      topic: "S&T",
      q: "Which of the following is/are famous for Sun temples?",
      options: ["Only Konark", "Konark and Modhera (among Indian examples)", "Only Nalanda mahavihara as a sun temple", "Only Jama Masjid"],
      answer: 1,
      solution: "Correct option: B. Culture map: Konark (Odisha), Modhera (Gujarat), Martand (Kashmir, ruins).",
    },
    {
      topic: "Polity",
      q: "Democracy’s most essential feature is:",
      options: ["A written constitution always", "Free and fair elections with one person one vote, plus rule of law", "A federal court only", "A planned economy"],
      answer: 1,
      solution: "Correct option: B. NCERT Democratic Politics: elections are necessary but not sufficient — rights and accountability complete it.",
    },
    {
      topic: "Geography",
      q: "Mediterranean climate is characterised by:",
      options: ["Rain throughout the year like equatorial rainforest", "Dry summer and wet winter", "Only polar night", "Monsoon reversal identical to India"],
      answer: 1,
      solution: "Correct option: B. West coasts ~30–40°: California, central Chile, Cape, SW Australia, Mediterranean basin.",
    },
  ], "Selected 2017 GS items with solutions."),
  pre("upsc", 2016, "GS Paper I (selected)", [
    {
      topic: "Polity",
      q: "Which of the following is/are among the Fundamental Duties of citizens?",
      options: ["To vote in every election mandatorily under the Constitution", "To uphold and protect the sovereignty, unity and integrity of India", "To pay income tax as a Fundamental Duty listed in 51A word for word as ‘GST’", "To join a political party"],
      answer: 1,
      solution: "Correct option: B. 51A(c) and neighbouring clauses. Voting is a statutory/constitutional right-duty mix, not copied as GST into 51A.",
    },
    {
      topic: "History",
      q: "The ‘Ghadar Party’ was formed in:",
      options: ["Pataliputra in 273 BCE", "North America by Indian emigrants (San Francisco etc.) before World War I", "London by the Cabinet Mission", "Dhaka in 1906 as the Muslim League"],
      answer: 1,
      solution: "Correct option: B. Revolutionary diaspora; Komagata Maru is the linked current of that story.",
    },
    {
      topic: "Economy",
      q: "There has been a persistent deficit budget year after year. Which action can help reduce the deficit?",
      options: ["Revenue expenditure increase with no receipts", "Raising tax revenue and/or cutting avoidable spending / better targeting of subsidies", "Only printing notes with no fiscal plan", "Abolishing the Budget"],
      answer: 1,
      solution: "Correct option: B. FRBM logic: quality of spending + tax base. Monetising deficit has inflation costs.",
    },
    {
      topic: "Environment",
      q: "On which of the following can you find the Bureau of Energy Efficiency Star Label?",
      options: ["Only aeroplanes", "Selected appliances such as ACs, refrigerators, etc.", "Only MGNREGA job cards", "Only passports"],
      answer: 1,
      solution: "Correct option: B. Standards and labelling under the Energy Conservation Act; BEE is the statutory agency.",
    },
    {
      topic: "Geography",
      q: "Which of the following is/are coastal processes?",
      options: ["Only glaciation in Antarctica", "Longshore drift, wave erosion and beach deposition", "Only jet streams", "Only El Niño"],
      answer: 1,
      solution: "Correct option: B. Class 11 geomorphology: destructive and constructive waves, spits, lagoons.",
    },
    {
      topic: "S&T",
      q: "Project Loon, sometimes in the news, was associated with:",
      options: ["Balloon-based internet experiments", "A nuclear missile", "A river interlink", "A GST Council seat"],
      answer: 1,
      solution: "Correct option: A. Digital divide / connectivity as GS-III. Treat company projects as application stories, not as current affairs forever.",
    },
    {
      topic: "Polity",
      q: "Which of the following statements is correct about the Lok Sabha?",
      options: ["Its maximum strength is fixed at 250 like Rajya Sabha", "It is the House to which the Council of Ministers is collectively responsible", "It cannot be dissolved", "Money Bills cannot originate there"],
      answer: 1,
      solution: "Correct option: B. Article 75: collective responsibility to Lok Sabha. That is the core of the parliamentary executive.",
    },
    {
      topic: "History",
      q: "Banjaras during the medieval period were:",
      options: ["Only temple architects of Khajuraho", "Trader-nomads who moved grain and goods with pack animals", "Only Mughal mansabdars of 5000 zat", "Portuguese cartographers"],
      answer: 1,
      solution: "Correct option: B. Themes in Indian History / NCERT: itinerant communities and the agrarian market.",
    },
  ], "Selected 2016 GS items with solutions."),
];

const upscMains = [
  mains("upsc", 2024, "GS-I", [
    { marks: 10, topic: "Ancient", q: "Underline the changes in the field of society and economy from the Rig Vedic to the later Vedic period.", solution: "Intro: pastoral janas → agrarian janapadas. Body: (i) iron, settled agriculture, land as wealth; (ii) varna crystallises, gotra, patriarchal household; (iii) rituals (srauta) and brahmana dominance; (iv) eastward shift to Ganga. Bihar hook: later Vedic sets the stage for mahajanapadas/Magadha. Close: continuity of cattle prestige with a new agrarian surplus." },
    { marks: 10, topic: "Culture", q: "Estimate the contribution of Pallavas of Kanchi for the development of art and literature of South India.", solution: "Mandapa and ratha experiments at Mahabalipuram; structural Shore Temple; Sanskrit and Tamil patronage (Mahendravarman as playwright). They are the bridge to Chola bronze-and-temple urbanism. Mention Chinese/SE Asian contacts lightly." },
    { marks: 10, topic: "Modern", q: "What were the events that led to the Quit India Movement? Point out its results.", solution: "Cripps failure, wartime inflation, Japanese threat, Gandhi’s ‘Do or Die’. 8 August 1942; mass upsurge, parallel governments, brutal suppression. Results: Congress banned, leaders jailed, but British legitimacy cracked; 1946 elections and Cabinet Mission follow. Bihar: 1942 underground activity." },
    { marks: 10, topic: "Geography", q: "What is sea surface temperature rise? How does it affect the formation of tropical cyclones?", solution: "SST is the skin temperature of the ocean mixed layer. Cyclones need ~26.5°C, low shear, Coriolis. Warmer SST → more latent heat, possibly higher intensity and rapid intensification; genesis location may shift. Bay of Bengal is India’s risk theatre." },
    { marks: 10, topic: "Society", q: "Why do large cities tend to attract more migrants than smaller towns? Discuss in the light of conditions in developing countries.", solution: "Agglomeration: jobs, education, hospitals, networks, informal entry. Cumulative causation (Myrdal). Push: agrarian distress. Developing-country flavour: informal housing, gig work, female independent migration. Policy: small-town employment, portable social security." },
    { marks: 10, topic: "Geography", q: "What is the phenomenon of ‘cloudbursts’? Explain.", solution: "Very high rainfall intensity over a small area/short time, often orographic + unstable moist air. Himalayan valleys: flash floods, landslides. Early warning, land-use, and not treating it as a ‘mystery’." },
    { marks: 10, topic: "Society", q: "What is the concept of a ‘demographic winter’? Is the world moving towards such a situation? Elaborate.", solution: "Prolonged below-replacement fertility, ageing, shrinking workforce. East Asia/Europe yes; Africa/parts of South Asia no. India is heterogeneous: south ageing faster than Bihar-UP. Policy: skills, care economy, not panic natalism alone." },
    { marks: 10, topic: "Society", q: "Distinguish between gender equality, gender equity and women’s empowerment. Why is it important to take gender concerns into account in programme design?", solution: "Equality: same treatment. Equity: fair treatment recognising disadvantage. Empowerment: agency over resources and body. Gender-blind schemes miss unpaid care, safety, land titles. Use sex-disaggregated data and GRB." },
    { marks: 15, topic: "Culture", q: "“Though the great Cholas are no more yet their name is still remembered with great pride because of their highest achievements in the domain of art and architecture.” Comment.", solution: "Brihadisvara, Gangaikondacholapuram, bronze Nataraja, temple as economic unit, naval SE Asia. Art is political theology plus artisan guilds. Close with living ritual at Thanjavur." },
    { marks: 15, topic: "World", q: "How far is it correct to say that the First World War was fought essentially for the preservation of balance of power?", solution: "Partly: alliance rigidity, naval race, Balkans. Also imperial markets, nationalism, blank cheque. India: men and material, Home Rule, 1919 reforms. Do not reduce to a single cause." },
    { marks: 15, topic: "Modern", q: "How far was the Industrial Revolution in England responsible for the decline of handicrafts and cottage industries in India?", solution: "Machine cloth + tariffs + railways as one-way trade; deindustrialisation debate (Nationalists vs Morris). Not the only cause: Company weavers’ coercion earlier. Link to GS-III MSME today." },
    { marks: 15, topic: "Geography", q: "The groundwater potential of the Gangetic valley is on a serious decline. How may it affect the food security of India?", solution: "Tube-well revolution, rice-wheat, electricity subsidy. Falling water tables → cost, arsenic/fluoride, rabi risk. Food security is availability + access + nutrition. Solutions: cropping shift, MIS, power reforms, Atal Bhujal flavour." },
  ], "Official 2024 GS-I questions with model-answer skeletons."),
  mains("upsc", 2024, "GS-II", [
    { marks: 10, topic: "Polity", q: "Examine the need for electoral reforms as suggested by various committees with particular reference to “one nation – one election”.", solution: "Committees: Tarkunde, Dinesh Goswami, Indrajit Gupta, Law Commission, EC proposals (criminalisation, funding). ONOP: cost, policy paralysis vs federal terms, constitutional amendments, Law Commission caution. Balanced close." },
    { marks: 10, topic: "Polity", q: "Explain and distinguish between Lok Adalats and Arbitration Tribunals. Whether they entertain civil as well as criminal cases?", solution: "Lok Adalat: Legal Services Authorities Act, conciliation, award = decree, compoundable criminal matters. Arbitration: Arbitration Act, private, contractual, civil/commercial — not criminal prosecution. Speed vs natural justice." },
    { marks: 10, topic: "Polity", q: "“The growth of cabinet system has practically resulted in the marginalisation of the parliamentary supremacy.” Elucidate.", solution: "Collective responsibility + majority → executive dominates legislative time. Anti-defection, ordinance, money bill route. Counter: committees, Rajya Sabha, judicial review. Reform: more committee hours." },
    { marks: 10, topic: "Polity", q: "“The duty of the CAG is not merely to ensure the legality of expenditure but also its propriety.” Comment.", solution: "Audit of regularity vs propriety/performance. 2nd ARC, CAG reports as PAC fuel. Limits: post-facto, not policy veto. Examples: defence, welfare leakage." },
    { marks: 10, topic: "Governance", q: "Analyse the role of local bodies in good governance at local level and the pros and cons of merging rural local bodies with urban local bodies.", solution: "73/74: proximity, 11th/12th Schedules. Merger: census towns, peri-urban services vs Gram Sabha identity, fiscal transfers. Bihar: rapidly urbanising blocks." },
    { marks: 10, topic: "IR", q: "Critically analyse India’s relations with the Central Asian Republics.", solution: "Connect Central Asia policy, INSTC, Chabahar, SCO, energy, extremism. Limits: geography, Pakistan/Afghanistan, China. Concrete projects over communiqués." },
    { marks: 15, topic: "Polity", q: "What are the aims of the Public Examinations (Prevention of Unfair Means) Act, 2024? Are University/State Board exams covered?", solution: "Paper leaks as a governance crisis (Bihar relevance). Act targets organised cheating in notified public exams. State boards/universities need notification/separate law — do not assume automatic coverage. Implementation + policing capacity." },
    { marks: 15, topic: "Rights", q: "Right to privacy is intrinsic to Article 21. Discuss DNA testing of a child in the womb to establish paternity.", solution: "Puttaswamy tests: legality, legitimate aim, proportionality. Foetal DNA: bodily autonomy of woman, best interests of child, dignity. Courts allow only when eminent need, not as a fishing enquiry." },
    { marks: 15, topic: "Federalism", q: "What changes has the Union recently introduced in Centre–State relations? Suggest measures to build trust.", solution: "GST, CSS, Governors, tax devolution, cesses, disaster funds. Measures: more tax devolution, fewer cesses, Inter-State Council, cooperative agencies, respect for elected state governments. Neutral tone." },
    { marks: 15, topic: "Judiciary", q: "Explain the growth of PIL. Has the Indian Supreme Court become the world’s most powerful judiciary?", solution: "Hussainara, Judges Transfer, epistolary jurisdiction, Article 21 expansion. Power: review of constitutional amendments, collegium, continuing mandamus. Limits: docket, enforcement, democratic critique of overreach." },
  ], "Official 2024 GS-II questions with model-answer skeletons."),
  mains("upsc", 2024, "GS-III", [
    { marks: 10, topic: "Economy", q: "Examine the pattern of public expenditure on social services in the post-reforms period. Has it served inclusive growth?", solution: "1991: fiscal squeeze then CSS expansion (education, health, NREGA, DBT). Outcomes: literacy/health gains with quality and jobless-growth gaps. Inclusive growth = jobs + human capital + regions. Cite Survey ratios, not slogans." },
    { marks: 10, topic: "Economy", q: "What are the causes of persistent high food inflation in India? Comment on RBI monetary policy effectiveness against it.", solution: "Supply: weather, proteins, logistics, MSP-procurement, global oils. Demand: rural wages. Repo is a blunt tool for vegetable shocks; buffers, imports, operation greens. MPC still anchors expectations." },
    { marks: 10, topic: "Agriculture", q: "Explain the role of millets for health and nutritional security in India.", solution: "Climate-smart, micronutrients, rainfed Bihar plateau fringe/Jharkhand. IYM 2023. Constraints: processing, taste, procurement. Link PDS diversification and anaemia." },
    { marks: 10, topic: "S&T", q: "What technology is used for electronic toll collection on highways? Advantages, limits, hazards?", solution: "FASTag/RFID. Time, fuel, leak-proof toll. Limits: KYC, blacklisting, privacy, local employment at plazas. Cyber and data localisation as hazards." },
    { marks: 15, topic: "Environment", q: "Industrial pollution of rivers is a significant issue. Discuss mitigation and government initiatives.", solution: "Effluent standards, CETP, CPCB/SPCB, NGT, Namami Gange, EPR. Enforcement gap. Bihar: Ganga stretches, tanneries/distilleries upstream. Combine law + financing + real-time monitoring." },
    { marks: 15, topic: "Security", q: "Explain how narco-terrorism has emerged as a threat. Suggest measures.", solution: "Golden Crescent/Triangle, drones, darknet, terror finance. Measures: NCB, FATF-style AML, border tech, demand-side health, coastal/airport scanning. Rights-compliant policing." },
    { marks: 15, topic: "Disaster", q: "Discuss disaster resilience. Mention elements of a resilience framework.", solution: "Sendai: understand risk, strengthen governance, invest, build back better. Structural vs non-structural. Bihar floods: embankment limits, early warning, shelters, insurance." },
  ], "Official 2024 GS-III themes with model-answer skeletons."),
  mains("upsc", 2024, "GS-IV", [
    { marks: 10, topic: "Ethics", q: "The application of AI as a dependable input for administrative decisions is debatable. Critically examine from an ethical point of view.", solution: "Pros: speed, pattern detection, leak-proof targeting. Cons: bias, opacity, accountability gap, exclusion errors. Ethical tests: fairness, explainability, human-in-loop, appeal. Example: welfare lists, policing." },
    { marks: 10, topic: "Ethics", q: "Global warming as an outcome of human greed — how do you restore equilibrium between society and environment?", solution: "Trusteeship, inter-generational equity, polluter pays, sufficiency. Policy: carbon price, just transition, adaptation in Bihar flood–heat geography. Personal: consumption ethic without sermonising." },
    { marks: 10, topic: "Thinkers", q: "“The concept of just and unjust is contextual… law should be constantly under scrutiny.” Examine.", solution: "Legal positivism vs natural justice. Constitutional morality (Ambedkar), basic structure, judicial review. Examples: emergency excesses, privacy, same-sex dignity. Scrutiny ≠ anarchy; it is democratic constitutionalism." },
    { marks: 15, topic: "Case", q: "A district officer must target flood relief when local elites capture lists. Outline the ethical decision process.", solution: "Facts → stakeholders (victims, panchayat, contractors, media) → options (do nothing, use SECC/GIS, social audit, FIR) → public interest + compassion + rule of law → communicate and monitor. Avoid partisanship." },
  ], "2024 GS-IV themes with operational answers."),
  mains("upsc", 2023, "GS-I", [
    { marks: 10, topic: "Culture", q: "Explain the role of geographical factors towards the development of Ancient India.", solution: "Monsoon agriculture, Himalaya–Ocean bounds, passes, rivers (Saraswati debate as geography not myth), coasts for trade. Magadha: iron, forests, Ganga–Son. Geography is possibility, not destiny." },
    { marks: 10, topic: "Modern", q: "What was the difference between Mahatma Gandhi and Rabindranath Tagore in their approach towards education and nationalism?", solution: "Gandhi: Nai Talim, vernacular, swaraj as self-rule of the self. Tagore: Visva-Bharati, world culture, critique of narrow nationalism. Both anti-colonial, different cosmopolitanisms." },
    { marks: 15, topic: "Society", q: "Why is caste identity in India both fluid and durable? Discuss.", solution: "Sanskritisation, politics, urban jobs vs endogamy, census/Mandal. Durable because it organises marriage and networks; fluid at the edges of class and region." },
  ], "Selected official 2023 GS-I questions."),
  mains("upsc", 2023, "GS-II", [
    { marks: 10, topic: "Polity", q: "“Constitutionally guaranteed judicial independence is a prerequisite of democracy.” Discuss.", solution: "Security of tenure, salaries, contempt, judicial review. Collegium vs NJAC. Independence is for the Constitution, not for the corporation of judges. Accountability via reasoned orders and integrity." },
    { marks: 15, topic: "IR", q: "The expansion and strengthening of NATO and a stronger US-Europe strategic partnership faces new challenges due to Russia’s invasion of Ukraine. Comment.", solution: "NATO rediscovery, energy shock, Global South unease, India’s strategic autonomy, food/fertiliser. Do not write a NATO press release; write India’s interest." },
  ], "Selected official 2023 GS-II questions."),
  mains("upsc", 2023, "GS-III", [
    { marks: 10, topic: "Economy", q: "Faster economic growth requires increased share of the manufacturing sector in GDP, particularly of MSMEs. Comment on the present policies.", solution: "Premature deindustrialisation risk, PLI, logistics, credit, labour. MSME: delayed payments, formalisation via GST/UPI. Jobs are the test." },
    { marks: 15, topic: "Security", q: "What are the internal security challenges being faced by India? Give out the role of Central and State agencies.", solution: "LWE, NE insurgency, terror, cyber, narcotics, communal. Federal policing: State list vs central forces, NIA, NATGRID flavour. Coordination and rights." },
  ], "Selected official 2023 GS-III questions."),
  mains("upsc", 2023, "GS-IV", [
    { marks: 10, topic: "Ethics", q: "What do you understand by ‘moral integrity’ and ‘professional efficiency’ in the context of corporate governance? Illustrate.", solution: "Integrity: honest reporting, related-party restraint. Efficiency: fiduciary duty to create value lawfully. Satyam vs well-run PSU/private boards. SEBI LODR as the hard shell of ethics." },
  ], "Selected official 2023 GS-IV questions."),
  mains("upsc", 2022, "GS-I", [
    { marks: 10, topic: "Culture", q: "How will you explain that medieval Indian temple sculptures represent the social life of those days?", solution: "Donors, dancers, warriors, erotic mithuna, caste guilds on walls. Temple as a social document, not only a deity. Compare Khajuraho, Konark, Hoysala." },
    { marks: 15, topic: "Geography", q: "Discuss the meaning of colour-coded weather warnings for cyclone prone areas given by IMD.", solution: "Green/yellow/orange/red: no action → watch → be prepared → take action. Link NDMA, last-mile in Odisha vs Bihar thunderstorms. Communication ethics: no panic, no complacency." },
  ], "Selected official 2022 GS-I questions."),
  mains("upsc", 2022, "GS-II", [
    { marks: 10, topic: "Polity", q: "The Attorney-General is the chief legal adviser of the Government. Discuss his roles and limitations.", solution: "Article 76, right of audience, aid and advice flavour but not a minister. Cannot vote in Parliament. Independence vs being the government’s lawyer — tension in politically charged references." },
    { marks: 15, topic: "IR", q: "Do you think that BIMSTEC is a parallel organisation like the SAARC? What are the popular theories about BIMSTEC?", solution: "BIMSTEC: Bay of Bengal, energy, connectivity, security — India can work without a SAARC veto. Not a clone; a pragmatic mini-lateral. Delivery on projects is the test." },
  ], "Selected official 2022 GS-II questions."),
  mains("upsc", 2021, "GS-I", [
    { marks: 10, topic: "Modern", q: "Trace the rise and growth of socio-religious reform movements with special reference to Young Bengal.", solution: "Derozio, rationalism, women’s education, against orthodoxy. Limits: elite, urban. Place beside Brahmo, Aligarh, Jyotiba Phule." },
    { marks: 15, topic: "Geography", q: "Differentiate the causes of landslides in the Himalayan region and Western Ghats.", solution: "Himalaya: young fold, earthquakes, rain, road cutting, dams. Ghats: laterite, rainfall, plantation, quarrying. Common: land-use. NDMA guidelines." },
  ], "Selected official 2021 GS-I questions."),
  mains("upsc", 2021, "GS-II", [
    { marks: 10, topic: "Polity", q: "‘Constitutional Morality’ is rooted in the Constitution itself and is to be found in the Preamble, the FRs and DPSPs. Comment.", solution: "Ambedkar: not public morality of the crowd. Examples: privacy, inclusion, anti-untouchability. Courts use it; critique: judicial subjectivity. Anchor in text." },
    { marks: 15, topic: "Governance", q: "Has digitalization empowered the Indian citizen? Discuss.", solution: "DBT, UPI, RTI online, CoWIN. Exclusion: authentication failures, connectivity, literacy. Empowerment needs grievance redress, not only apps." },
  ], "Selected official 2021 GS-II questions."),
  mains("upsc", 2020, "GS-I", [
    { marks: 10, topic: "Culture", q: "Persian literary sources of medieval India reflect the spirit of the age. Comment.", solution: "Court chronicles (Barani, Abul Fazl) as ideology; travelogues; sufi tazkiras. Bias of patronage. Use alongside inscriptions and architecture." },
    { marks: 15, topic: "Society", q: "Do you agree that regionalism in India appears to be a consequence of rising cultural assertiveness? Discuss.", solution: "Language, statehood, development lag, political mobilisation. Not only culture: fiscal federalism and migration (Bihar). Accommodation via States Reorganisation and 73rd." },
  ], "Selected official 2020 GS-I questions."),
  mains("upsc", 2020, "GS-II", [
    { marks: 10, topic: "Polity", q: "Rajya Sabha has been transformed from a ‘useless stepney tyre’ to an indispensably important institution. Comment.", solution: "Federal second chamber, revision, 249/312, experienced members. Still: money bill disputes, disruptions. Strengthen committees rather than abolish." },
    { marks: 15, topic: "IR", q: "‘Quadrilateral Security Dialogue (Quad)’ is transforming itself into a trade block from a military alliance, in present times. Discuss.", solution: "Quad is not NATO. Vaccines, infrastructure, maritime domain awareness, critical tech. India keeps strategic autonomy and Russia/China realities. Call it a coalition of interests." },
  ], "Selected official 2020 GS-II questions."),
  mains("upsc", 2019, "GS-I", [
    { marks: 10, topic: "Ancient", q: "Highlight the Central Asian and Greco-Bactrian elements in the Gandhara art.", solution: "Hellenistic drapery, Buddha as Apollo-like, schist, narrative Jatakas. Syncretic Silk Road. Contrast Mathura red sandstone." },
    { marks: 15, topic: "World", q: "Explain how the foundations of the modern world were laid by the American and French Revolutions.", solution: "Rights, constitution, nation, citizen. Limits: slavery, colonial France. India: liberal vocabulary of Moderates; later mass politics exceeds it." },
  ], "Selected official 2019 GS-I questions."),
  mains("upsc", 2019, "GS-II", [
    { marks: 10, topic: "Polity", q: "Do you think the Constitution of India does not accept the principle of strict separation of powers? Discuss.", solution: "Functional overlap: ordinance, delegated legislation, judicial review, parliamentary privileges. Checks, not Chinese walls. Contrast US. Basic structure still protects each organ’s core." },
    { marks: 15, topic: "IR", q: "‘The time has come for India and Japan to build a strong contemporary relationship.’ In the light of this, discuss economic, cultural and defence aspects.", solution: "Act East, corridors, bullet train flavour, Quad, defence logistics. Culture: Buddhism. Caveats: trade imbalance, China hedging." },
  ], "Selected official 2019 GS-II questions."),
  mains("upsc", 2018, "GS-I", [
    { marks: 10, topic: "Culture", q: "Safeguarding the Indian art heritage is the need of the moment. Discuss.", solution: "Thefts, pollution, urbanisation, poor documentation. ASI, AMASR, UNESCO, community arts (Madhubani). Heritage as livelihood, not only monuments." },
    { marks: 15, topic: "Society", q: "‘Caste system is assuming new identities and associational forms. Hence, the caste system cannot be eradicated in India.’ Comment.", solution: "From ritual hierarchy to political blocs and matrimonial markets. Law (17, PoA) plus economy plus education. Eradication is a horizon; reduction of humiliation is the metric." },
  ], "Selected official 2018 GS-I questions."),
  mains("upsc", 2018, "GS-II", [
    { marks: 10, topic: "Polity", q: "In the light of recent controversy regarding the use of Electronic Voting Machines (EVM), what are the challenges before the Election Commission?", solution: "Trust is the product. VVPAT, mock polls, audits, communication. Challenge: rumour vs evidence. EC independence and logistics in heat/floods." },
    { marks: 15, topic: "Governance", q: "E-governance is not just about routine application of digital technology; it is as much about interactions for transparency. Comment.", solution: "G2C/G2G, interactive service model, RTI + dashboards, social audit. Failure modes: dashboards without grievance. Bihar service delivery examples, non-partisan." },
  ], "Selected official 2018 GS-II questions."),
];

const bpscExtra = [
  pre("bpsc", 2022, "67th/68th GS (selected)", [
    {
      topic: "Bihar history",
      q: "The capital of Magadha was shifted from Rajagriha to Pataliputra mainly because of:",
      options: ["A cooler climate in the Himalaya", "Strategic control of the Ganga–Son corridor and river trade", "Portuguese ports", "The discovery of petroleum"],
      answer: 1,
      solution: "Correct option: B. Ajatashatru/Udayin tradition: riverine fort and trade. Core BPSC ancient-history item.",
    },
    {
      topic: "Modern",
      q: "Kunwar Singh is remembered in 1857 primarily for operations around:",
      options: ["Mysore", "Jagdishpur–Arrah (Bhojpur) in Bihar", "Peshawar", "Calicut"],
      answer: 1,
      solution: "Correct option: B. Age, guerrilla style, alliance with sepoys. Pair with Babu Amar Singh.",
    },
    {
      topic: "Geography",
      q: "The Kosi is often called the ‘sorrow of Bihar’ because of:",
      options: ["Coral bleaching", "Shifting course, heavy sediment and floods", "Desertification of the Thar", "Tidal bores"],
      answer: 1,
      solution: "Correct option: B. Avulsion + embankment politics + disaster management.",
    },
    {
      topic: "Polity",
      q: "The 73rd Constitutional Amendment is related to:",
      options: ["GST", "Panchayati Raj", "Finance Commission only", "Official language"],
      answer: 1,
      solution: "Correct option: B. Part IX, 11th Schedule. Bihar PRIs and women’s reservation are standard follow-ups.",
    },
    {
      topic: "Economy",
      q: "A major feature of Bihar’s contemporary economy is:",
      options: ["Highest factory share in India always", "High out-migration and remittance dependence with a thin industrial base", "No agriculture", "A desert economy"],
      answer: 1,
      solution: "Correct option: B. Use Economic Survey of Bihar numbers when you quote.",
    },
    {
      topic: "Culture",
      q: "Madhubani (Mithila) painting traditionally uses:",
      options: ["Only oil on canvas in Paris", "Natural colours and ritual-wall/paper painting of Mithila", "Only Mughal miniature paper from Agra", "Warli of Maharashtra exclusively"],
      answer: 1,
      solution: "Correct option: B. GI and livelihood; do not confuse with Kalighat or Kalamkari.",
    },
    {
      topic: "Environment",
      q: "Arsenic contamination in parts of the Ganga plains is mainly linked to:",
      options: ["Ozone hole", "Groundwater chemistry in alluvial aquifers", "Volcanoes in Patna", "Coral reefs"],
      answer: 1,
      solution: "Correct option: B. Public-health geography: wells, mitigation, surface-water options.",
    },
    {
      topic: "Modern",
      q: "Champaran Satyagraha (1917) was directed against:",
      options: ["Salt monopoly in Dandi only", "European indigo planters and tinkathia", "Only the Rowlatt Act", "Only Simon Commission"],
      answer: 1,
      solution: "Correct option: B. Enquiry, agreement, first satyagraha in India.",
    },
  ], "High-yield Bihar GS items that repeat across recent BPSC prelims cycles."),
  mains("bpsc", 2024, "GS (Mains)", [
    { marks: 8, topic: "History", q: "Discuss the significance of Magadha in the making of the first pan-Indian state.", solution: "Iron, elephants, Ganga–Son, Nanda–Maurya administration, spies and revenue. Ashoka’s dhamma as public communication. Archaeological: Rajgir, Kumrahar." },
    { marks: 8, topic: "Modern", q: "Evaluate the contribution of Bihar in the Revolt of 1857.", solution: "Kunwar Singh, Arrah siege, Danapur sepoys. Peasant–taluqdar mix. Aftermath: Crown rule, army reorganisation. Local, not a footnote to Meerut." },
    { marks: 8, topic: "Geography", q: "Explain the flood problem of North Bihar and suggest a sustainable strategy.", solution: "Himalayan rivers, sediment, embankment-induced waterlogging. Mix: warning, shelters, room for the river, transboundary data with Nepal, insurance, not only higher bunds." },
    { marks: 8, topic: "Economy", q: "Account for out-migration from Bihar. What state policies can make growth more job-rich?", solution: "Push: land, floods, weak industry. Pull: Punjab, Delhi, Gulf. Skills, food processing, logistics, tourism (Nalanda–Bodh Gaya), urban services. Remittances as a bridge, not a destiny." },
    { marks: 8, topic: "Polity", q: "Examine the working of Panchayati Raj in Bihar after the 73rd Amendment.", solution: "Reservations, mukhiya politics, funds/functions/functionaries gap, parallel missions. Success: participation of women. Reform: own revenues, audit, Gram Sabha vitality." },
    { marks: 8, topic: "Ethics", q: "A District Magistrate faces pressure to inflate flood-relief lists. What values will guide you?", solution: "Integrity, compassion for the real poor, courage, objectivity. Tools: SECC, geo-tag, social audit, written file. Communicate why lists were trimmed. No party colour." },
  ], "BPSC mains-style GS file with model solutions (Bihar paper)."),
  mains("bpsc", 2023, "GS (Mains)", [
    { marks: 8, topic: "Culture", q: "Write a note on Nalanda as a centre of learning and its contemporary relevance.", solution: "Mahavihara, patrons, Xuanzang, curriculum, destruction narratives with care. New Nalanda University: internationalisation vs heritage conservation." },
    { marks: 8, topic: "Modern", q: "Champaran Satyagraha was more than an indigo dispute. Discuss.", solution: "Planters, tinkathia, peasant evidence, Gandhi’s method, nationalisation of a local grievance. Template for later satyagrahas." },
    { marks: 8, topic: "Society", q: "Discuss caste and politics in Bihar without partisanship.", solution: "Social justice coalitions, census debate, development vs identity. GS needs institutions and dignity, not slogans." },
    { marks: 8, topic: "S&T", q: "How can space technology help Bihar’s disaster and agriculture administration?", solution: "Flood inundation maps, crop insurance, weather nowcast. ISRO + state disaster authority. Last-mile is still the gram panchayat." },
    { marks: 8, topic: "Environment", q: "Gangetic dolphin as a flagship — conservation challenges in Bihar.", solution: "Vikramshila sanctuary, river traffic, pollution, gill nets. Flagship for a living Ganga, not a poster only." },
  ], "69th-cycle mains themes with model solutions."),
];

export const extraBank = {
  upsc: [...upscPrelims, ...upscMains],
  bpsc: bpscExtra,
};
